commented Force Failure

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -24,5 +24,5 @@ jobs:
       - name: Run Tests
         run: npm run test
     
-      - name: Force Failure
-        run: (exit 1)
+    #   - name: Force Failure
+    #     run: (exit 1)
